#!/usr/bin/env python3
"""
BinBench Semantic Analyzer.

Produces:
- result_analysis.md
- result_metrics.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
import sys
from difflib import SequenceMatcher
from typing import Dict, List, Optional, Tuple
from urllib.parse import unquote_to_bytes

from semantic_utils import (
    classify_scalar,
    normalize_whitespace,
    parse_source_context,
    parse_stdout_cases,
    summarize_args,
    summarize_regs,
)
from trace_format import SEMANTIC_ANALYSIS_VERSION


class TraceParser:
    """Parse trace files generated by hook_trace.js."""

    def __init__(self, filepath: str):
        self.filepath = filepath
        self.calls: List[Dict[str, object]] = []
        self.errors: List[str] = []
        self.entry_count = 0
        self.exit_count = 0
        self.print_count = 0
        self.parse()

    def parse(self) -> None:
        ent_pattern = re.compile(r'TRACE_ENT\|(\d+)\|([^\|]+)\|(\d+)\|([^\|]*)(?:\|(.*))?$')
        ext_pattern = re.compile(r'TRACE_EXT\|(\d+)\|([^\|]+)\|(\d+)\|(.+)$')
        print_pattern = re.compile(r'TRACE_PRINT\|(\d+)\|(.*)$')
        error_pattern = re.compile(r'ERROR: (.+)')
        pending: Dict[int, Dict[str, object]] = {}
        orphan_prints = 0

        with open(self.filepath, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue

                error_match = error_pattern.match(line)
                if error_match:
                    self.errors.append(error_match.group(1))
                    continue

                match_ent = ent_pattern.match(line)
                if match_ent:
                    self.entry_count += 1
                    seq = int(match_ent.group(1))
                    call = {
                        "seq": seq,
                        "name": match_ent.group(2),
                        "depth": int(match_ent.group(3)),
                        "args": self._parse_key_values(match_ent.group(4)),
                        "regs": self._parse_key_values(match_ent.group(5), base=0),
                        "ret": None,
                        "prints": [],
                    }
                    pending[seq] = call
                    continue

                match_print = print_pattern.match(line)
                if match_print:
                    self.print_count += 1
                    seq = int(match_print.group(1))
                    content = self._decode_print(match_print.group(2))
                    if seq in pending:
                        pending[seq].setdefault("prints", []).append(content)
                    else:
                        orphan_prints += 1
                    continue

                match_ext = ext_pattern.match(line)
                if match_ext:
                    self.exit_count += 1
                    seq = int(match_ext.group(1))
                    ret_str = match_ext.group(4)
                    ret = self._parse_scalar(ret_str)
                    if seq in pending:
                        pending[seq]["ret"] = ret
                        self.calls.append(pending.pop(seq))
                    else:
                        self.calls.append(
                            {
                                "seq": seq,
                                "name": match_ext.group(2),
                                "depth": int(match_ext.group(3)),
                                "args": {},
                                "regs": {},
                                "ret": ret,
                                "prints": [],
                            }
                        )

        for seq in sorted(pending):
            self.calls.append(pending[seq])

        self.calls.sort(key=lambda item: item["seq"])
        if orphan_prints:
            self.errors.append(f"orphan TRACE_PRINT events: {orphan_prints}")

    def _parse_scalar(self, value: str):
        try:
            return int(value, 0)
        except Exception:
            return value

    def _parse_key_values(self, values: Optional[str], base: Optional[int] = None) -> Dict[str, object]:
        if not values:
            return {}

        result: Dict[str, object] = {}
        for part in values.split(","):
            if "=" not in part:
                continue
            key, raw_value = part.split("=", 1)
            key = key.strip()
            raw_value = raw_value.strip()
            try:
                if base is None:
                    result[key] = int(raw_value)
                else:
                    result[key] = int(raw_value, base)
            except Exception:
                result[key] = raw_value
        return result

    def _decode_print(self, value: str) -> str:
        try:
            raw = unquote_to_bytes(value)
        except Exception:
            return value
        try:
            return raw.decode("utf-8")
        except UnicodeDecodeError:
            return raw.decode("latin-1")


def load_json_if_exists(path: str) -> Dict[str, object]:
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def atomic_write_text(path: str, content: str) -> None:
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".tmp-", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def atomic_write_json(path: str, payload: Dict[str, object]) -> None:
    atomic_write_text(path, json.dumps(payload, indent=2, ensure_ascii=False))


class SemanticAnalyzer:
    PROGRAM_STDOUT_MAX_PARSE_BYTES = 1_000_000
    FUNCTION_LEVEL_MAX_CALLS_PER_SIDE = 5000
    LOW_LEVEL_MAX_TOKENS_PER_SIDE = 5000

    def __init__(self, base_dir: str):
        self.base_dir = base_dir
        self.context = load_json_if_exists(os.path.join(base_dir, "semantic_context.json"))
        self.source_path = self.context.get("source_path") or ""
        self.source_context = parse_source_context(self.source_path) if self.source_path else {
            "drivers": [],
            "unstable_case_ids": [],
            "stable_case_ids": [],
        }
        self.arch = self._infer_architecture()
        self.word_bits = self._infer_word_bits()
        self.program_runs = {
            "original": load_json_if_exists(os.path.join(base_dir, "program_original.json")),
            "decompiled": load_json_if_exists(os.path.join(base_dir, "program_decompiled.json")),
        }
        self.trace_original = TraceParser(os.path.join(base_dir, "trace_original.txt"))
        self.trace_decompiled = TraceParser(os.path.join(base_dir, "trace_decompiled.txt"))
        self.trace_health = self._build_trace_health()

    def _infer_architecture(self) -> Optional[str]:
        arch = self.context.get("arch")
        if isinstance(arch, str) and arch:
            return arch
        for part in os.path.normpath(self.base_dir).split(os.sep):
            if part in {"arm64", "arm32", "x64", "x86"}:
                return part
        return None

    def _infer_word_bits(self) -> Optional[int]:
        if self.arch in {"arm32", "x86", "arm", "ia32"}:
            return 32
        if self.arch in {"arm64", "x64"}:
            return 64
        return None

    def analyze(self) -> Tuple[Dict[str, object], str]:
        program_level = self._analyze_program_level()
        function_level = self._analyze_function_level()
        low_level = self._analyze_low_level(function_level)
        quality_status = self._derive_quality_status(program_level, function_level)

        metrics = {
            "execution_status": "success",
            "quality_status": quality_status,
            "analysis_version": SEMANTIC_ANALYSIS_VERSION,
            "trace_format_version": self.context.get("trace_format_version"),
            "trace_capture_mode": self.context.get("trace_capture_mode"),
            "source_path": self.source_path,
            "drivers": self.source_context.get("drivers", []),
            "trace_health": self.trace_health,
            "program_level": program_level,
            "function_level": function_level,
            "low_level": low_level,
        }

        report = self._build_report(metrics)
        return metrics, report

    def _program_run_issue(self, run: Dict[str, object]) -> str:
        if not run:
            return "missing_run"

        stderr = str(run.get("stderr") or "")
        if run.get("timed_out"):
            return "timeout"
        if stderr.startswith("Binary not found:"):
            return "missing_binary"
        if "GLIBC_" in stderr:
            return "glibc_mismatch"
        if "Exec format error" in stderr or "cannot execute binary file" in stderr:
            return "exec_format_error"

        signal_value = run.get("signal")
        if signal_value is not None:
            return f"signal_{signal_value}"

        exit_code = run.get("exit_code")
        if exit_code not in (None, 0):
            return f"exit_{exit_code}"

        return "ok"

    def _program_run_incomparable(self, run: Dict[str, object]) -> bool:
        issue = self._program_run_issue(run)
        return issue in {
            "missing_run",
            "timeout",
            "missing_binary",
            "glibc_mismatch",
            "exec_format_error",
        }

    def _analyze_program_level(self) -> Dict[str, object]:
        original = self.program_runs["original"]
        decompiled = self.program_runs["decompiled"]
        stable_case_ids = set(self.source_context.get("stable_case_ids", []))
        unstable_case_ids = set(self.source_context.get("unstable_case_ids", []))
        original_stdout = original.get("stdout", "")
        decompiled_stdout = decompiled.get("stdout", "")
        stdout_nonempty_original = bool(normalize_whitespace(original_stdout))
        stdout_nonempty_decompiled = bool(normalize_whitespace(decompiled_stdout))

        process_match = (
            original.get("exit_code") == decompiled.get("exit_code")
            and original.get("signal") == decompiled.get("signal")
            and bool(original) and bool(decompiled)
        )
        raw_stdout_exact_match = original_stdout == decompiled_stdout
        original_run_issue = self._program_run_issue(original)
        decompiled_run_issue = self._program_run_issue(decompiled)
        decompiled_incomparable = self._program_run_incomparable(decompiled)

        if (
            len(original_stdout) > self.PROGRAM_STDOUT_MAX_PARSE_BYTES
            or len(decompiled_stdout) > self.PROGRAM_STDOUT_MAX_PARSE_BYTES
        ):
            if decompiled_incomparable and not stdout_nonempty_decompiled:
                status = "unsupported"
            elif stdout_nonempty_decompiled and raw_stdout_exact_match:
                status = "exact"
            else:
                status = "fail"
            return {
                "status": status,
                "comparison_key": "test_id+occurrence",
                "comparison_denominator_policy": "stdout_guard",
                "process_status_match": process_match,
                "stdout_exact_match": status == "exact",
                "raw_stdout_exact_match": raw_stdout_exact_match,
                "stdout_nonempty_original": stdout_nonempty_original,
                "stdout_nonempty_decompiled": stdout_nonempty_decompiled,
                "stdout_case_match_ratio": 1.0 if status == "exact" else 0.0,
                "stable_case_total": 0,
                "stable_case_matched": 0,
                "original_stable_case_total": 0,
                "decompiled_stable_case_total": 0,
                "stable_case_ids": sorted(stable_case_ids),
                "unstable_case_ids": sorted(unstable_case_ids),
                "original_exit_code": original.get("exit_code"),
                "decompiled_exit_code": decompiled.get("exit_code"),
                "original_signal": original.get("signal"),
                "decompiled_signal": decompiled.get("signal"),
                "original_run_issue": original_run_issue,
                "decompiled_run_issue": decompiled_run_issue,
                "comparisons_total": 0,
                "comparisons": [],
                "skipped_reason": (
                    f"stdout_exceeds_{self.PROGRAM_STDOUT_MAX_PARSE_BYTES}:"
                    f"{len(original_stdout)}/{len(decompiled_stdout)}"
                ),
            }

        orig_cases = parse_stdout_cases(original_stdout)
        dec_cases = parse_stdout_cases(decompiled_stdout)

        orig_stable = {
            (case["test_id"], case["occurrence"]): case
            for case in orig_cases
            if case["test_id"] in stable_case_ids
        }
        dec_stable = {
            (case["test_id"], case["occurrence"]): case
            for case in dec_cases
            if case["test_id"] in stable_case_ids
        }
        original_stable_case_total = len(orig_stable)
        decompiled_stable_case_total = len(dec_stable)

        matched = 0
        comparisons: List[Dict[str, object]] = []
        case_keys: List[Tuple[str, int]] = []
        for case in orig_cases:
            key = (case["test_id"], case["occurrence"])
            if case["test_id"] in stable_case_ids and key not in case_keys:
                case_keys.append(key)
        for case in dec_cases:
            key = (case["test_id"], case["occurrence"])
            if case["test_id"] in stable_case_ids and key not in case_keys:
                case_keys.append(key)

        for test_id, occurrence in case_keys:
            orig_case = orig_stable.get((test_id, occurrence))
            dec_case = dec_stable.get((test_id, occurrence))
            same = bool(orig_case and dec_case and orig_case["normalized"] == dec_case["normalized"])
            if same:
                matched += 1

            comparisons.append(
                {
                    "test_id": test_id,
                    "occurrence": occurrence,
                    "original": (orig_case or {}).get("raw"),
                    "decompiled": (dec_case or {}).get("raw"),
                    "matched": same,
                }
            )

        denominator = len(case_keys)
        match_ratio = matched / denominator if denominator else 0.0

        if denominator > 0:
            if matched == denominator and decompiled_stable_case_total > 0:
                status = "exact"
            elif matched > 0:
                status = "partial"
            elif decompiled_incomparable and decompiled_stable_case_total == 0 and not stdout_nonempty_decompiled:
                status = "unsupported"
            else:
                status = "fail"
        elif decompiled_incomparable:
            status = "unsupported"
        elif not stdout_nonempty_decompiled:
            status = "fail"
        else:
            status = "unsupported"

        return {
            "status": status,
            "comparison_key": "test_id+occurrence",
            "comparison_denominator_policy": "stable_case_union",
            "process_status_match": process_match,
            "stdout_exact_match": status == "exact",
            "raw_stdout_exact_match": raw_stdout_exact_match,
            "stdout_nonempty_original": stdout_nonempty_original,
            "stdout_nonempty_decompiled": stdout_nonempty_decompiled,
            "stdout_case_match_ratio": round(match_ratio, 4),
            "stable_case_total": denominator,
            "stable_case_matched": matched,
            "original_stable_case_total": original_stable_case_total,
            "decompiled_stable_case_total": decompiled_stable_case_total,
            "stable_case_ids": sorted(stable_case_ids),
            "unstable_case_ids": sorted(unstable_case_ids),
            "original_exit_code": original.get("exit_code"),
            "decompiled_exit_code": decompiled.get("exit_code"),
            "original_signal": original.get("signal"),
            "decompiled_signal": decompiled.get("signal"),
            "original_run_issue": original_run_issue,
            "decompiled_run_issue": decompiled_run_issue,
            "comparisons_total": len(comparisons),
            "comparisons": comparisons,
        }

    def _trace_side_health(self, label: str, parser: TraceParser) -> Dict[str, object]:
        run_summary = (self.context.get("trace_runs") or {}).get(label, {})
        issues: List[str] = []
        warnings: List[str] = []
        parser_error_count = len(parser.errors)
        if run_summary and run_summary.get("status") != "success":
            issues.append("trace_run_failed")
        if parser_error_count:
            issues.append("trace_parse_errors")
        if not parser.calls:
            issues.append("no_calls_captured")
        if run_summary:
            if run_summary.get("entry_count") != parser.entry_count:
                warnings.append("entry_count_mismatch")
            if run_summary.get("exit_count") != parser.exit_count:
                warnings.append("exit_count_mismatch")
            if run_summary.get("print_count") != parser.print_count:
                warnings.append("print_count_mismatch")

        return {
            "run_status": run_summary.get("status", "unknown"),
            "usable": not issues,
            "event_count": run_summary.get("event_count", parser.entry_count + parser.exit_count + parser.print_count),
            "entry_count": run_summary.get("entry_count", parser.entry_count),
            "exit_count": run_summary.get("exit_count", parser.exit_count),
            "print_count": run_summary.get("print_count", parser.print_count),
            "call_count": len(parser.calls),
            "parsed_entry_count": parser.entry_count,
            "parsed_exit_count": parser.exit_count,
            "parsed_print_count": parser.print_count,
            "parser_error_count": parser_error_count,
            "run_error": run_summary.get("error"),
            "issues": issues,
            "warnings": warnings,
        }

    def _build_trace_health(self) -> Dict[str, object]:
        original = self._trace_side_health("original", self.trace_original)
        decompiled = self._trace_side_health("decompiled", self.trace_decompiled)

        usable = original["usable"] and decompiled["usable"]
        if usable:
            status = "available"
        elif original["usable"] or decompiled["usable"]:
            status = "partial"
        else:
            status = "unavailable"

        return {
            "status": status,
            "usable_for_structural_evidence": usable,
            "original": original,
            "decompiled": decompiled,
        }

    def _function_level_unavailable(self, skipped_reason: Optional[str] = None) -> Dict[str, object]:
        payload = {
            "status": "unavailable",
            "segment_count": len(self.source_context.get("drivers", [])),
            "segment_callseq_match_ratio": None,
            "feature_function_match_ratio": None,
            "call_evidence_segment_count": 0,
            "call_evidence_unavailable_count": len(self.source_context.get("drivers", [])),
            "segment_print_match_ratio": None,
            "segment_print_evidence_count": 0,
            "segment_print_unavailable_count": len(self.source_context.get("drivers", [])),
            "normalized_io_match_ratio": 0.0,
            "io_matched_pairs": 0,
            "io_compared_pairs": 0,
            "trace_errors": {
                "original": len(self.trace_original.errors),
                "decompiled": len(self.trace_decompiled.errors),
            },
            "segments": [],
        }
        if skipped_reason:
            payload["skipped_reason"] = skipped_reason
        return payload

    def _extract_segments(self, parser: TraceParser) -> Dict[str, Dict[str, object]]:
        drivers = self.source_context.get("drivers", [])
        segments = {
            driver: {
                "driver_call": None,
                "calls": [],
            }
            for driver in drivers
        }
        current_driver = None

        for call in parser.calls:
            if call["depth"] == 0:
                if call["name"] in segments:
                    current_driver = call["name"]
                    segments[current_driver]["driver_call"] = call
                else:
                    current_driver = None
                continue
            if current_driver is not None and call["depth"] > 0:
                segments[current_driver]["calls"].append(call)
        return segments

    def _call_signature(self, call: Dict[str, object]) -> str:
        return f"{call['name']}|a{','.join(summarize_args(call['args'], word_bits=self.word_bits))}"

    def _normalized_print_lines(self, call: Optional[Dict[str, object]]) -> Tuple[str, ...]:
        if not call:
            return tuple()

        content = "".join(call.get("prints") or [])
        lines: List[str] = []
        previous = None
        for raw_line in content.splitlines():
            normalized = normalize_whitespace(raw_line.strip())
            if normalized:
                if normalized == previous:
                    continue
                lines.append(normalized)
                previous = normalized
        return tuple(lines)

    def _print_match_ratio(self, left: Optional[Dict[str, object]], right: Optional[Dict[str, object]]) -> Optional[float]:
        left_lines = self._normalized_print_lines(left)
        right_lines = self._normalized_print_lines(right)
        if not left_lines and not right_lines:
            return None
        return SequenceMatcher(a=left_lines, b=right_lines).ratio()

    def _format_ratio(self, value: Optional[float]) -> str:
        if value is None:
            return "N/A"
        return f"{value:.4f}"

    def _io_signature(self, call: Dict[str, object]) -> str:
        args_sig = ",".join(summarize_args(call["args"], word_bits=self.word_bits))
        ret_sig = classify_scalar(call.get("ret"), word_bits=self.word_bits)
        print_sig = "||".join(self._normalized_print_lines(call))
        return f"{call['name']}|{args_sig}|ret={ret_sig}|prints={print_sig}"

    def _align_common_names(self, left: List[Dict[str, object]], right: List[Dict[str, object]]) -> Tuple[int, int]:
        left_names = [call["name"] for call in left]
        right_names = [call["name"] for call in right]
        matcher = SequenceMatcher(a=left_names, b=right_names)
        matched_names = 0
        matched_io = 0

        for opcode, i1, i2, j1, j2 in matcher.get_opcodes():
            if opcode != "equal":
                continue
            segment_left = left[i1:i2]
            segment_right = right[j1:j2]
            for lcall, rcall in zip(segment_left, segment_right):
                matched_names += 1
                if self._io_signature(lcall) == self._io_signature(rcall):
                    matched_io += 1

        return matched_names, matched_io

    def _analyze_function_level(self) -> Dict[str, object]:
        drivers = self.source_context.get("drivers", [])

        if not drivers:
            return {
                "status": "unsupported",
                "segment_count": 0,
                "segment_callseq_match_ratio": None,
                "feature_function_match_ratio": None,
                "call_evidence_segment_count": 0,
                "call_evidence_unavailable_count": 0,
                "segment_print_match_ratio": None,
                "segment_print_evidence_count": 0,
                "segment_print_unavailable_count": 0,
                "normalized_io_match_ratio": 0.0,
                "io_matched_pairs": 0,
                "io_compared_pairs": 0,
                "trace_errors": {
                    "original": len(self.trace_original.errors),
                    "decompiled": len(self.trace_decompiled.errors),
                },
                "segments": [],
            }

        if not self.trace_health.get("usable_for_structural_evidence"):
            return self._function_level_unavailable()

        if (
            len(self.trace_original.calls) > self.FUNCTION_LEVEL_MAX_CALLS_PER_SIDE
            or len(self.trace_decompiled.calls) > self.FUNCTION_LEVEL_MAX_CALLS_PER_SIDE
        ):
            return self._function_level_unavailable(
                skipped_reason=(
                    f"call_count_exceeds_{self.FUNCTION_LEVEL_MAX_CALLS_PER_SIDE}:"
                    f"{len(self.trace_original.calls)}/{len(self.trace_decompiled.calls)}"
                )
            )

        original_segments = self._extract_segments(self.trace_original)
        decompiled_segments = self._extract_segments(self.trace_decompiled)

        segment_results = []
        total_seq_ratio = 0.0
        total_match_ratio = 0.0
        call_evidence_count = 0
        total_print_ratio = 0.0
        print_evidence_count = 0
        total_io_matched = 0
        total_io_compared = 0

        for driver in drivers:
            orig_segment = original_segments.get(driver, {})
            dec_segment = decompiled_segments.get(driver, {})
            orig_calls = orig_segment.get("calls", [])
            dec_calls = dec_segment.get("calls", [])
            call_evidence_available = bool(orig_calls or dec_calls)
            orig_signatures = [self._call_signature(call) for call in orig_calls]
            dec_signatures = [self._call_signature(call) for call in dec_calls]
            seq_ratio = (
                SequenceMatcher(a=orig_signatures, b=dec_signatures).ratio()
                if call_evidence_available
                else None
            )
            print_ratio = self._print_match_ratio(orig_segment.get("driver_call"), dec_segment.get("driver_call"))
            print_evidence_available = print_ratio is not None

            orig_names = [call["name"] for call in orig_calls]
            dec_names = [call["name"] for call in dec_calls]
            matched_names, matched_io = self._align_common_names(orig_calls, dec_calls)
            match_ratio = (
                (2 * matched_names / (len(orig_names) + len(dec_names)))
                if call_evidence_available and (orig_names or dec_names)
                else None
            )

            if seq_ratio is not None:
                total_seq_ratio += seq_ratio
                total_match_ratio += match_ratio or 0.0
                call_evidence_count += 1
            if print_evidence_available:
                total_print_ratio += print_ratio
                print_evidence_count += 1
            total_io_matched += matched_io
            total_io_compared += matched_names

            if not orig_calls and not dec_calls and not print_evidence_available:
                seg_status = "unsupported"
            elif (
                call_evidence_available
                and seq_ratio == 1.0
                and match_ratio == 1.0
                and matched_io == matched_names
                and (print_ratio is None or print_ratio == 1.0)
            ):
                seg_status = "pass"
            elif (
                (call_evidence_available and matched_names > 0)
                or (print_evidence_available and print_ratio > 0.0)
            ):
                seg_status = "partial"
            else:
                seg_status = "fail"

            segment_results.append(
                {
                    "segment": driver,
                    "status": seg_status,
                    "call_evidence_available": call_evidence_available,
                    "original_call_count": len(orig_calls),
                    "decompiled_call_count": len(dec_calls),
                    "original_print_count": len(self._normalized_print_lines(orig_segment.get("driver_call"))),
                    "decompiled_print_count": len(self._normalized_print_lines(dec_segment.get("driver_call"))),
                    "sequence_match_ratio": round(seq_ratio, 4) if seq_ratio is not None else None,
                    "feature_match_ratio": round(match_ratio, 4) if match_ratio is not None else None,
                    "print_evidence_available": print_evidence_available,
                    "driver_print_match_ratio": round(print_ratio, 4) if print_ratio is not None else None,
                    "matched_io_pairs": matched_io,
                    "matched_name_pairs": matched_names,
                }
            )

        segment_count = len(drivers)
        avg_seq_ratio = total_seq_ratio / call_evidence_count if call_evidence_count else None
        avg_match_ratio = total_match_ratio / call_evidence_count if call_evidence_count else None
        avg_print_ratio = total_print_ratio / print_evidence_count if print_evidence_count else None
        io_ratio = total_io_matched / total_io_compared if total_io_compared else 0.0

        if segment_count == 0:
            status = "unsupported"
        elif all(segment["status"] == "unsupported" for segment in segment_results):
            status = "unsupported"
        elif all(segment["status"] == "pass" for segment in segment_results):
            status = "pass"
        elif any(segment["status"] in ("pass", "partial") for segment in segment_results):
            status = "partial"
        else:
            status = "fail"

        return {
            "status": status,
            "segment_count": segment_count,
            "segment_callseq_match_ratio": round(avg_seq_ratio, 4) if avg_seq_ratio is not None else None,
            "feature_function_match_ratio": round(avg_match_ratio, 4) if avg_match_ratio is not None else None,
            "call_evidence_segment_count": call_evidence_count,
            "call_evidence_unavailable_count": segment_count - call_evidence_count,
            "segment_print_match_ratio": round(avg_print_ratio, 4) if avg_print_ratio is not None else None,
            "segment_print_evidence_count": print_evidence_count,
            "segment_print_unavailable_count": segment_count - print_evidence_count,
            "normalized_io_match_ratio": round(io_ratio, 4),
            "io_matched_pairs": total_io_matched,
            "io_compared_pairs": total_io_compared,
            "trace_errors": {
                "original": len(self.trace_original.errors),
                "decompiled": len(self.trace_decompiled.errors),
            },
            "segments": segment_results,
        }

    def _low_level_tokens(self, parser: TraceParser) -> List[str]:
        tokens = []
        drivers = set(self.source_context.get("drivers", []))
        for call in parser.calls:
            if call["name"] in drivers:
                continue
            reg_sig = ",".join(summarize_regs(call["regs"], word_bits=self.word_bits))
            ret_sig = classify_scalar(call.get("ret"), word_bits=self.word_bits)
            tokens.append(f"{call['name']}|{reg_sig}|ret={ret_sig}")
        return tokens

    def _analyze_low_level(self, function_level: Dict[str, object]) -> Dict[str, object]:
        if function_level.get("status") == "unsupported":
            return {
                "status": "unsupported",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": 0,
                "token_count_decompiled": 0,
            }
        if function_level.get("status") == "unavailable":
            return {
                "status": "unavailable",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": 0,
                "token_count_decompiled": 0,
            }

        original_tokens = self._low_level_tokens(self.trace_original)
        decompiled_tokens = self._low_level_tokens(self.trace_decompiled)
        original_run = self.program_runs["original"]
        decompiled_run = self.program_runs["decompiled"]
        process_status_match = (
            original_run.get("exit_code") == decompiled_run.get("exit_code")
            and original_run.get("signal") == decompiled_run.get("signal")
            and bool(original_run) and bool(decompiled_run)
        )

        if not original_tokens and not decompiled_tokens:
            return {
                "status": "unsupported" if process_status_match else "unavailable",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": 0,
                "token_count_decompiled": 0,
            }

        if original_tokens and not decompiled_tokens:
            return {
                "status": "unavailable",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": len(original_tokens),
                "token_count_decompiled": 0,
            }

        if decompiled_tokens and not original_tokens:
            return {
                "status": "unavailable",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": 0,
                "token_count_decompiled": len(decompiled_tokens),
            }

        if (
            len(original_tokens) > self.LOW_LEVEL_MAX_TOKENS_PER_SIDE
            or len(decompiled_tokens) > self.LOW_LEVEL_MAX_TOKENS_PER_SIDE
        ):
            return {
                "status": "unavailable",
                "method": "normalized_register_signature_sequence",
                "similarity_score": None,
                "token_count_original": len(original_tokens),
                "token_count_decompiled": len(decompiled_tokens),
                "skipped_reason": f"token_count_exceeds_{self.LOW_LEVEL_MAX_TOKENS_PER_SIDE}",
            }

        score = SequenceMatcher(a=original_tokens, b=decompiled_tokens).ratio() if (original_tokens or decompiled_tokens) else 1.0

        return {
            "status": "available",
            "method": "normalized_register_signature_sequence",
            "similarity_score": round(score, 4),
            "token_count_original": len(original_tokens),
            "token_count_decompiled": len(decompiled_tokens),
        }

    def _derive_quality_status(self, program_level: Dict[str, object], function_level: Dict[str, object]) -> str:
        program_status = program_level["status"]
        normalized_program_status = "pass" if program_status in {"pass", "exact"} else program_status

        if normalized_program_status == "fail":
            return "fail"
        if normalized_program_status == "unsupported":
            if function_level["status"] == "fail":
                return "fail"
            if function_level["status"] in ("unsupported", "unavailable"):
                return "unsupported"
            return "partial"
        if function_level["status"] == "fail":
            return "partial" if normalized_program_status in ("pass", "partial") else "fail"
        if function_level["status"] == "unavailable":
            return "partial"
        if normalized_program_status == "pass" and function_level["status"] == "pass":
            return "pass"
        return "partial"

    def _build_report(self, metrics: Dict[str, object]) -> str:
        program = metrics["program_level"]
        function = metrics["function_level"]
        low_level = metrics["low_level"]
        trace_health = metrics["trace_health"]
        lines = [
            "# Semantic Evaluation Report",
            "",
            "## Executive Summary",
            "",
            f"- Execution Status: `{metrics['execution_status']}`",
            f"- Quality Status: `{metrics['quality_status']}`",
            f"- Analysis Version: `{metrics.get('analysis_version')}`",
            f"- Program-Level: `{program['status']}`",
            f"- Function-Level: `{function['status']}`",
            f"- Low-Level: `{low_level['status']}`",
            f"- Trace Health: `{trace_health['status']}`",
            "",
            "## 1. Program-Level Evidence",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Comparison Key | `{program.get('comparison_key')}` |",
            f"| Denominator Policy | `{program.get('comparison_denominator_policy')}` |",
            f"| Process Status Match | {program['process_status_match']} |",
            f"| Comparable Stdout Exact Match | {program['stdout_exact_match']} |",
            f"| Raw Stdout Exact Match | {program.get('raw_stdout_exact_match')} |",
            f"| Stdout Nonempty (Original) | {program.get('stdout_nonempty_original')} |",
            f"| Stdout Nonempty (Decompiled) | {program.get('stdout_nonempty_decompiled')} |",
            f"| Stable Case Match Ratio | {program['stdout_case_match_ratio']:.4f} |",
            f"| Stable Cases | {program['stable_case_matched']} / {program['stable_case_total']} |",
            f"| Original Stable Cases Observed | {program.get('original_stable_case_total', 0)} |",
            f"| Decompiled Stable Cases Observed | {program.get('decompiled_stable_case_total', 0)} |",
            f"| Original Run Issue | `{program.get('original_run_issue')}` |",
            f"| Decompiled Run Issue | `{program.get('decompiled_run_issue')}` |",
            f"| Comparison Records | {program['comparisons_total']} |",
            "",
            "## 2. Trace Health",
            "",
            f"- Structural Evidence Usable: `{trace_health['usable_for_structural_evidence']}`",
            f"- Original Trace: `{trace_health['original']['run_status']}` / calls={trace_health['original']['call_count']} / parser_errors={trace_health['original']['parser_error_count']}",
            f"- Decompiled Trace: `{trace_health['decompiled']['run_status']}` / calls={trace_health['decompiled']['call_count']} / parser_errors={trace_health['decompiled']['parser_error_count']}",
            f"- Original Trace Warnings: `{', '.join(trace_health['original'].get('warnings', [])) or 'none'}`",
            f"- Decompiled Trace Warnings: `{', '.join(trace_health['decompiled'].get('warnings', [])) or 'none'}`",
            "",
            "## 3. Function-Level Evidence",
            "",
            f"- Call-Evidence Segments: `{function.get('call_evidence_segment_count', 0)} / {function.get('segment_count', 0)}`",
            f"- Average Segment Call Sequence Ratio: `{self._format_ratio(function['segment_callseq_match_ratio'])}`",
            f"- Average Feature Function Match Ratio: `{self._format_ratio(function.get('feature_function_match_ratio'))}`",
            f"- Average Driver Print Match Ratio: `{self._format_ratio(function['segment_print_match_ratio'])}`",
            f"- Driver Print Evidence Segments: `{function.get('segment_print_evidence_count', 0)} / {function.get('segment_count', 0)}`",
                f"- Normalized IO Match Ratio: `{function['normalized_io_match_ratio']:.4f}` ({function.get('io_matched_pairs', 0)} / {function.get('io_compared_pairs', 0)} matched-name pairs)",
            "",
            "| Segment | Status | Call Evidence | Orig Calls | Decomp Calls | Orig Prints | Decomp Prints | Seq Ratio | Match Ratio | Print Ratio | IO Matches |",
            "|---------|--------|---------------|------------|--------------|-------------|---------------|-----------|-------------|-------------|------------|",
        ]

        for segment in function.get("segments", []):
            lines.append(
                f"| `{segment['segment']}` | {segment['status']} | {segment.get('call_evidence_available')} | {segment['original_call_count']} | "
                f"{segment['decompiled_call_count']} | {segment['original_print_count']} | "
                f"{segment['decompiled_print_count']} | {self._format_ratio(segment['sequence_match_ratio'])} | "
                f"{self._format_ratio(segment.get('feature_match_ratio'))} | {self._format_ratio(segment['driver_print_match_ratio'])} | "
                f"{segment['matched_io_pairs']} / {segment['matched_name_pairs']} |"
            )

        lines.extend(
            [
                "",
                "## 4. Low-Level Evidence",
                "",
                "| Metric | Value |",
                "|--------|-------|",
                f"| Method | `{low_level['method']}` |",
                f"| Similarity Score | {low_level['similarity_score']} |",
                f"| Token Count (Orig) | {low_level['token_count_original']} |",
                f"| Token Count (Decomp) | {low_level['token_count_decompiled']} |",
                "",
                "## 5. Notes",
                "",
                f"- Trace format version: `{metrics.get('trace_format_version')}` ({metrics.get('trace_capture_mode') or 'unknown'})",
                f"- Analysis version: `{metrics.get('analysis_version')}`",
                "- Program-level metrics only count stable test items from the explicit stability configuration when available.",
                "- Program-level case alignment keys by `(test_id, occurrence)` and uses the union of stable cases observed on either side as the denominator.",
                "- Program-level `comparisons` are retained in full and `comparisons_total` records the exact count for auditability.",
                "- UB / platform-dependent / signal / subprocess / threading-heavy cases are recorded but excluded from the program-level denominator.",
                "- Driver print evidence is reported as unavailable when both sides capture no print lines; this is not treated as a perfect match.",
                "- Driver-level print comparison only collapses consecutive duplicate normalized lines inside the same trace segment; raw program stdout remains available separately for program-level auditing.",
                "- Call-sequence and feature-match aggregates exclude segments with no call evidence, so fully inlined segments no longer inflate those ratios.",
                "- Feature-function match is symmetric: extra calls on either side lower the score; the earlier redundant `feature_*_hit_ratio` alias has been removed.",
                "- If program-level evidence passes but function-level hooks fail to line up, the overall result degrades to partial rather than fail.",
                "- If program-level evidence is partial but function-level hooks fail completely, the overall result still remains partial because some stable program-level evidence matched.",
                "- If program-level evidence exists but trace capture is unavailable, function-level and low-level evidence are marked unavailable and the overall result degrades to partial.",
                "- If both program-level and function-level evidence are unsupported, the top-level quality status is `unsupported` rather than `partial`.",
                "- If program-level evidence is unsupported but function-level evidence is present, the top-level quality status stays `partial`: this means function-only evidence, not program-output equivalence.",
                "- Low-level similarity uses `SequenceMatcher` over normalized tokens, so scores are length-sensitive and diagnostic-only rather than directly comparable to program-level pass rates.",
                "- Scalar normalization is word-width aware for 32-bit and 64-bit traces before applying the coarse `PTR` bucket, reducing false pointer matches from unsigned wraparound values.",
                "- `normalized_io_match_ratio` is computed as matched I/O signatures divided by matched-name pairs across all segments; because print strings are compared exactly after normalization, this metric is intentionally conservative for `%p`-style output.",
                "- Low-level similarity is diagnostic-only and does not participate in pass/fail thresholding.",
            ]
        )
        return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze BinBench semantic traces")
    parser.add_argument("output_dir", nargs="?", help="Directory containing semantic outputs")
    args = parser.parse_args()

    base_dir = args.output_dir or os.path.abspath(os.path.join(os.path.dirname(__file__), "../../results/semantic"))

    trace_orig_path = os.path.join(base_dir, "trace_original.txt")
    trace_decomp_path = os.path.join(base_dir, "trace_decompiled.txt")
    report_path = os.path.join(base_dir, "result_analysis.md")
    metrics_path = os.path.join(base_dir, "result_metrics.json")

    if not os.path.exists(trace_orig_path) or not os.path.exists(trace_decomp_path):
        print(f"Error: Trace files not found in {base_dir}")
        return 1

    analyzer = SemanticAnalyzer(base_dir)
    metrics, report = analyzer.analyze()

    atomic_write_text(report_path, report)
    atomic_write_json(metrics_path, metrics)

    print(f"Analysis complete. Report generated at {report_path}")
    print(f"Metrics generated at {metrics_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
